name: Build and Deploy CC Open Source
on: [push, pull_request]
jobs:
 build-and-deploy:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - name: setup python version
     uses: actions/setup-python@v3
     with:
      python-version: 3.9
   - name: Install dependencies
     run: |
      pip install pipenv
      pipenv sync
      pipenv run lektor build -f webpack
   - name: Deploy to production
     if: github.ref == 'refs/heads/main'
     run: |
      pipenv run lektor deploy ghpages --username ${{ secrets.LEKTOR_DEPLOY_USERNAME }} --password ${{ secrets.LEKTOR_DEPLOY_PASSWORD }}
